<a href="https://colab.research.google.com/github/wooookim/GoogleCloud_AI/blob/main/0104(pandas).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np

In [ ]:
'''
판다스
- 데이터 조작및 분석 기능을 제공
- 다양한 형식의 데이터를 읽고 원하는데이터 형식으로 변환하는 작업
- 자료구조: series, dataframe
'''

In [15]:
'''
Series 객체
- 1차원 배열 같은 자료구조 객체
'''
obj = Series([3, 22, 34, 11])
objj = Series(np.array([3, 22, 34,11]))
arr = np.array([3, 22, 34,11])
obj, arr, objj

(0     3
 1    22
 2    34
 3    11
 dtype: int64,
 array([ 3, 22, 34, 11]),
 0     3
 1    22
 2    34
 3    11
 dtype: int64)

In [14]:
print(obj.values)
print(obj.index)

[ 3 22 34 11]
RangeIndex(start=0, stop=4, step=1)


In [18]:
'''
index를 RangeIndex 객체로 관리 -> 수정 가능
'''
obj2 = Series([4, 5, 6, 2], index = ['c', 'd', 'e', 'f'])
obj2

c    4
d    5
e    6
f    2
dtype: int64

In [22]:
# indexing
print(obj2['c'], obj2[0])

4 4


In [23]:
# 배열연산
obj2 * 2

c     8
d    10
e    12
f     4
dtype: int64

In [25]:
# 파이썬 리스트 연산과 구분 필요
[1, 2, 3] * 2

TypeError: ignored

In [26]:
# 슬라이싱
obj2[0:2]

c    4
d    5
dtype: int64

In [27]:
# 연속적이지 않은 데이터 지정
obj2[[0,2,1]]

c    4
e    6
d    5
dtype: int64

In [28]:
arr[0]

3

In [29]:
arr[0:2]

array([ 3, 22])

In [30]:
arr[[0, 2, 1]]

array([ 3, 34, 22])

In [31]:
# 인덱스 존재 여부 확인: 불리언 반환
print(1 in obj2)

False


In [36]:
print('c' in obj2)  #요소, 인덱스 둘 다 확인 가능

True


In [38]:
# 파이썬 딕셔너리 자료형으로 Series 객체 생성 가능
data = {'kim':3400, 'hong':2000, 'kang':1000, 'lee':2400}

obj3 = Series(data)
obj3

kim     3400
hong    2000
kang    1000
lee     2400
dtype: int64

In [40]:
# Series index가 바뀌면 key가 사라지는 결과가 되므로 value가 NaN 처림됨
name = ['woo', 'hong', 'kang',' lee']
obj4 = Series(data, index = name)
obj4

woo        NaN
hong    2000.0
kang    1000.0
 lee       NaN
dtype: float64

In [44]:
'''
결츨치를 찾을 때
- isnull, notnull : 불리언 반환
'''
print(pd.isnull(obj4))
print(pd.notnull(obj4))
print(pd.isna(obj4))
print(pd.notna(obj4))

woo      True
hong    False
kang    False
 lee     True
dtype: bool
woo     False
hong     True
kang     True
 lee    False
dtype: bool
woo      True
hong    False
kang    False
 lee     True
dtype: bool
woo     False
hong     True
kang     True
 lee    False
dtype: bool


In [49]:
# 정리
data = {'서울':4000,'부산':2000,'인천':1500,'제주':1000}
obj = Series(data)
print(obj)
print(obj.index, '-', obj.values)
print('-'*20)

cities = ['서울', '대구', '인천', '제주']
obj2 = Series(data, index = cities)
print(obj2)
print('-'*20)

# nan은 연산되지 않음
obj + obj2

서울    4000
부산    2000
인천    1500
제주    1000
dtype: int64
Index(['서울', '부산', '인천', '제주'], dtype='object') - [4000 2000 1500 1000]
--------------------
서울    4000.0
대구       NaN
인천    1500.0
제주    1000.0
dtype: float64
--------------------


대구       NaN
부산       NaN
서울    8000.0
인천    3000.0
제주    2000.0
dtype: float64

In [51]:
# Series 객체와 Index 객체 모두 name 속성이 있음
obj2.name = '인구수'
obj2

obj2.index.name = '도시'
obj2

도시
서울    4000.0
대구       NaN
인천    1500.0
제주    1000.0
Name: 인구수, dtype: float64

In [52]:
# key-value로 지정하면서 바로 key를 바꾸면 nan 처리될 수 있지만, 따로 index만 바꾸는 것은 가능
obj2.index = ['대전', '부산', '전주', '광주']
obj2

대전    4000.0
부산       NaN
전주    1500.0
광주    1000.0
Name: 인구수, dtype: float64

In [53]:
'''
DataFrame 객체
- 2차원 리스트(배열) 같은 자료구조 객체
'''
x = DataFrame(
    [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]
)
x

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [59]:
# 딕셔너리로도 데이터프레임 생성 가능
data = {
    'city': ['서울', '부산', '광주', '대구'],    # 데이터 타입
    'year': [2000, 2001, 2002, 2002],
    'pop': [4000, 2000, 1000, 1000]
}
df = DataFrame(data)
df

city  year   pop
0   서울  2000  4000
1   부산  2001  2000
2   광주  2002  1000
3   대구  2002  1000