<a href="https://colab.research.google.com/github/wooookim/GoogleCloud_AI/blob/main/0104(numpy_%EC%8B%A4%EC%8A%B5).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
# 대각선 방향의 값이 1이고, 나머지 값은 0인 10x10 2차원 array를 생성하여 6번째 행을 출력하시오.
# 예상출력 : [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]

In [10]:
np.eye(10), np.eye(10)[5]

(array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]]),
 array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]))

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [ ]:
#길이가 10인 모든 값이 1인 1 차원 array를 생성하시오.
#예상출력 : [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]







[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [19]:
#길이가 10인 모든 값이 1인 1 차원 array를 생성하시오.
#예상출력 : [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
np.array([1 for i in range(10)])

np.diag(np.identity(10))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
#i행 j열의 값이 2i + 3j 인 10x10 2차원 array를 생성하여 마지막 열을 출력하시오.
#예상출력 : [18 21 24 27 30 33 36 39 42 45]







[[ 0  3  6  9 12 15 18 21 24 27]
 [ 2  5  8 11 14 17 20 23 26 29]
 [ 4  7 10 13 16 19 22 25 28 31]
 [ 6  9 12 15 18 21 24 27 30 33]
 [ 8 11 14 17 20 23 26 29 32 35]
 [10 13 16 19 22 25 28 31 34 37]
 [12 15 18 21 24 27 30 33 36 39]
 [14 17 20 23 26 29 32 35 38 41]
 [16 19 22 25 28 31 34 37 40 43]
 [18 21 24 27 30 33 36 39 42 45]]
[18 21 24 27 30 33 36 39 42 45]


In [39]:
#i행 j열의 값이 2i + 3j 인 10x10 2차원 array를 생성하여 마지막 열을 출력하시오.
#예상출력 : [18 21 24 27 30 33 36 39 42 45]



array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [ ]:
# 공백으로 구분된 정수들을 입력 받아 1차원 리스트에 저장하고, 최댓값의 index를 출력하세요. NumPy 함수를 이용해 아래 문제를 해결하시오.
# numpy 문서를 참조하세요
# 입력예시 : 1 85 0 91 4
# 정답출력 : 3






1 85 0 91 4
3
