<a href="https://colab.research.google.com/github/wooookim/GoogleCloud_AI/blob/main/0104(numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [145]:
import numpy as np

In [146]:
'''
표준수학 함수
- 기술통계
'''
x = np.array([1,3,4,5,32,24,36,78,56,4,5,6,34,5,3,6,34,56,25,27])

len(x)
np.mean(x)
np.average(x)
np.var(x)  # 분산: 데이터와 샘플 평균 간 거리 차이의 제곱합
np.std(x)  # 표준편차: 분산의 제곱근
np.max(x)
np.min(x)
np.median(x)  # 짝수는 2개 중앙값 평균
np.quantile(x, [.25, .5, .75])
np.percentile(x, [0, 25, 50, 75, 100])
np.sum(x)
np.product(x)  # 전체곱

6918345990382551040

In [147]:
'''
선형대수
- 벡터, 행렬, 선형 변환, 선형 방정식

데이터 유형
1. 스칼라: 하나의 숫자로 이루어진 데이터
2. 벡터: 여러개의 숫자로 이루어진 데이터, data record
3. 행렬: 벡터가 여러개 있는 데이터 집합
'''

'\n선형대수\n- 벡터, 행렬, 선형 변환, 선형 방정식\n\n데이터 유형\n1. 스칼라: 하나의 숫자로 이루어진 데이터\n2. 벡터: 여러개의 숫자로 이루어진 데이터, data record\n3. 행렬: 벡터가 여러개 있는 데이터 집합\n'

In [148]:
# 스칼라
x = 1
x

1

In [149]:
# 벡터
x = np.array([2, 2, 3])
x

# 선형대수에서는 벡터를 표현할  때 열의개수가 하나인 2차원 배열 형태로 표현을 권장
# -> 벡터 = 열벡터
x = np.array([[2],[2],[3]])
x
# rank가 1인 배열 객체도 대부분 벡터로 인정

array([[2],
       [2],
       [3]])

In [150]:
# 행렬
x = np.array([[2, 2],[3, 3], [4, 4]])
x

array([[2, 2],
       [3, 3],
       [4, 4]])

In [151]:
# 전치행렬
x.T

array([[2, 3, 4],
       [2, 3, 4]])

In [152]:
'''
특수한 벡터와 행렬

- 영벡터: 모든 원소가 0인 n차원 벡터
- 일벡터: 모든 원소가 1인 n차원 벡터

- 영행렬: 모든 원소가 0인 n차원 행렬
- 일행렬: 모든 원소가 1인 n차원 행렬
- 정방행렬: 행의 개수와 열의 개수가 같은 행렬
- 대각행렬: 모든 비대각 요소(off-diagnol)가 0인 정방 행렬
  - 단위행렬: 대각행렬중에서 모든 대각 요소(주요소) 값이 1인 대각행렬
- 대칭행렬: 원 행렬과 이 행렬을 전치 연산한 전치행렬이 같은 행렬
'''

'\n특수한 벡터와 행렬\n\n- 영벡터: 모든 원소가 0인 n차원 벡터\n- 일벡터: 모든 원소가 1인 n차원 벡터\n\n- 영행렬: 모든 원소가 0인 n차원 행렬\n- 일행렬: 모든 원소가 1인 n차원 행렬\n- 정방행렬: 행의 개수와 열의 개수가 같은 행렬\n- 대각행렬: 모든 비대각 요소(off-diagnol)가 0인 정방 행렬\n  - 단위행렬: 대각행렬중에서 모든 대각 요소(주요소) 값이 1인 대각행렬\n- 대칭행렬: 원 행렬과 이 행렬을 전치 연산한 전치행렬이 같은 행렬\n'

In [153]:
# 영행렬
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [154]:
# 일행렬
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [155]:
# 특정 상수 행렬
np.full((3, 3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [156]:
# 대각행렬
np.diag((1, 2))
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [157]:
# 단위 행렬
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [158]:
I = np.identity(3)
np.diag(I)

array([1., 1., 1.])

In [159]:
'''
벡터 내적
- 합성곱
- 결과행렬은 앞 행렬의 행벡터와 뒤 행렬의 열벡터를 내적한 값을 스칼라로 가지는 행렬
'''
x = np.array([[1,2], [3,4]])
y = np.array([9, 10])

print(x * y)
# 내적
print(np.dot(x, y))

[[ 9 20]
 [27 40]]
[29 67]


In [160]:
'''
브로드캐스팅
- 모양이 다른 배열들 간의 연산이 어떤 조건을 만족했을 때 가능하도록 배열을 자동 변환
- 조건
  1. 한 쪽 차원 크기가 1, 즉 스칼라일 경우
  2. 차원의 크기가 1이 아닐 경우, 차원의 짝이 맞는 조건 필요(축의 길이가 같을 경우)
'''

'\n브로드캐스팅\n- 모양이 다른 배열들 간의 연산이 어떤 조건을 만족했을 때 가능하도록 배열을 자동 변환\n- 조건\n  1. 한 쪽 차원 크기가 1, 즉 스칼라일 경우\n  2. 차원의 크기가 1이 아닐 경우, 차원의 짝이 맞는 조건 필요(축의 길이가 같을 경우)\n'

In [161]:
# 한 쪽이 스칼라인 경우
a = np.array([[1, 2], [3, 4]])
b = 10

a + b

array([[11, 12],
       [13, 14]])

In [162]:
# 축의 길이가 같은 경우
c = np.array([[1, 2], [3, 4]])
d = np.array([1, 2])

c + d

array([[2, 4],
       [4, 6]])

In [163]:
# 차원이 1이 아니라면
a = np.array([1, 2, 3, 4])
b = np.array([1, 2])

a + b

ValueError: ignored

In [164]:
x = np.ones((3,3))
y = 5

x * y

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [165]:
y = np.arange(3)

x + y

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [166]:
x = np.arange(3).reshape(3, 1)
y = np.arange(3)

x, y, x + y

(array([[0],
        [1],
        [2]]),
 array([0, 1, 2]),
 array([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]]))

In [167]:
'''
차원축소 연산

행렬의 하나의 행에 있는 원소들을 데이터 집합으로 보고 그집합의 평균을 구하면 각 집합당 하나의 값이 나고게 되고, 그 값들만 따로 데이터 집합으로 두면 차원 축소가 된다

활용 매서드
1. argmin: 최소값 위치
2. argmax: 최대값 위치
3. all/any: 참/거짓

축 지정
- axis
'''
x = np.array([0, 1, 10, 100])
x.min()
x.max()
x.argmin()
x.argmax()
x.all()

False

In [168]:
# all
# 배열의 모든 요소가 True인지 평가하는 함수
np.all([True, True, False])

False

In [169]:
# any
np.any([True, True, False])

True

In [170]:
# axis
x = np.array([[1,1], [2,2]])
x.sum(axis = 0)  # 열
x.sum(axis = 1)  # 행

array([2, 4])

In [171]:
'''
넘파이 데이터 자료형

dtype 속성에서 첫글자 부여
- b: boolian
- i: integer
- f: floating-point(부동소수점)
- c: 복소수 부동소수점
- o: 객체
- s: 바이트 문자열
- U: 유니코드 문자열

- inf: 무한대
- NaN: Not a Number
- N/A: Not Available, Not Applicable
'''

'\n넘파이 데이터 자료형\n\ndtype 속성에서 첫글자 부여\n- b: boolian\n- i: integer\n- f: floating-point(부동소수점)\n- c: 복소수 부동소수점\n- o: 객체\n- s: 바이트 문자열\n- U: 유니코드 문자열\n\n- inf: 무한대\n- NaN: Not a Number\n- N/A: Not Available, Not Applicable\n'

In [172]:
x = np.array([1, 2, 3])
x.dtype

dtype('int64')

In [173]:
x = np.array([1, 2, 3.0])
x.dtype

dtype('float64')

In [174]:
x = np.array([1, 'A', 3.0])
x.dtype

dtype('<U32')

In [175]:
# 형변환
x = np.array([1., 2.55, 3.], dtype = 'i')
x

array([1, 2, 3], dtype=int32)

In [176]:
x[0] + x[1]

3

In [177]:
np.array([0,1,-1,0] / np.array([1,0,0,0]))

<ipython-input-177-9894390229ba>:1: RuntimeWarning: divide by zero encountered in divide
  np.array([0,1,-1,0] / np.array([1,0,0,0]))
<ipython-input-177-9894390229ba>:1: RuntimeWarning: invalid value encountered in divide
  np.array([0,1,-1,0] / np.array([1,0,0,0]))


array([  0.,  inf, -inf,  nan])

In [178]:
'''
넘파이 제공 함수
- 난수
'''

'\n넘파이 제공 함수\n- 난수\n'

In [179]:
# 난수
np.random.seed(42)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [183]:
np.random.seed(0)
np.random.rand(5), np.random.rand(5)

(array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ]),
 array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152]))

In [184]:
np.random.seed(2)
np.random.rand(5), np.random.rand(5)

(array([0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ]),
 array([0.33033482, 0.20464863, 0.61927097, 0.29965467, 0.26682728]))

In [188]:
for i in range(10):
  print(np.random.rand())

np.random.rand(10)

0.7367470562871129
0.37921056694163746
0.01301733669455063
0.7974049390325936
0.2693887975963012
0.5826848885290346
0.025550941849692754
0.6622020192683258
0.3875234258732815
0.49707379873451263


array([0.41490584, 0.3508719 , 0.55097791, 0.97291069, 0.11277622,
       0.31325853, 0.04179771, 0.73839976, 0.65751239, 0.21463575])

In [192]:
# shuffle
x = np.arange(10)

np.random.shuffle(x)
x

array([7, 4, 3, 8, 6, 0, 2, 9, 5, 1])

In [236]:
'''
데이터 샘플링
- 이미 있는 데이터 집합에서 무작위로 선택
'''
np.random.choice(x, 10, replace = False)   # 매개변수 (원본데이터, 추출 크기, 반복 여부)
np.random.choice(5, 5, replace = True)   # 추출크기가 데이터보다 크면 replace는 True로 설정해서 출력할 것
np.random.choice(5, 5, replace = True, p=[0.1,0,0,0.3,0.6])   # 매개변수 p로 출현 확률 지정

array([4, 4, 4, 4, 4])

In [199]:
np.random.sample(10)

array([0.37304105, 0.01080092, 0.84846201, 0.24316678, 0.68002726,
       0.67713974, 0.88582741, 0.15356567, 0.94669413, 0.29374373])

In [240]:
'''
rand(): 0 ~ 1 실수 - 균일분표
randn(): 실수 - 가우시안 표준 정규 분포
randint(): 정수 - 균일분포
  - randint(low, high, size)
'''
np.random.rand(5), np.random.rand(3, 5)

(array([0.50019799, 0.03946572, 0.2132418 , 0.36899204, 0.84760649]),
 array([[8.75681081e-01, 4.68470246e-04, 4.09984329e-01, 8.89430601e-01,
         5.85167789e-01],
        [7.46897743e-01, 5.87851237e-01, 4.27534542e-01, 5.33218220e-01,
         9.56540057e-01],
        [8.78180153e-01, 6.61060882e-01, 5.03271951e-01, 9.61353847e-02,
         9.17164663e-01]]))

In [243]:
np.random.randn(10), np.random.randn(3, 5)

(array([-0.76943903,  0.92972459, -0.67442578, -0.9691591 ,  0.68532759,
        -0.59252473, -1.0295358 ,  0.7756705 ,  1.48963864, -0.99523812]),
 array([[ 0.06317524,  0.78620946, -1.13084313, -1.14226477, -0.56311206],
        [-1.07598965, -0.35646002, -0.44051842, -0.52201472, -0.77702207],
        [ 2.03102386, -1.93032647,  0.55992704, -0.33445787, -1.81422349]]))

In [248]:
np.random.randint(10, 50, 5)

array([39, 14, 35, 46, 38])

In [260]:
'''
[실습]
로또 5천원어치
'''
np.random.randint(1, 46, (5, 6)), np.random.randint(1, 46, [5, 6])

(array([[24, 35, 44, 23, 18, 11],
        [16, 43, 21, 10,  3, 35],
        [10, 31,  4, 20, 28, 39],
        [13,  7, 39, 44, 22,  4],
        [ 2,  7, 29, 18, 25, 12]]),
 array([[39, 41,  8,  3, 11, 16],
        [ 3,  7, 36, 38, 18,  3],
        [11, 42,  1, 30, 22, 44],
        [15,  7, 34, 23, 23,  4],
        [26,  3, 40, 30, 29, 42]]))

In [262]:
# 랜덤값으로 채운 행렬
np.empty((3, 2))

array([[7.91e-323, 3.46e-323],
       [9.88e-323, 1.93e-322],
       [1.78e-322, 8.89e-323]])

In [268]:
'''
정렬 sort
'''
a = np.array([[4,3,5,6],[1,12,11,9],[2,15,1,18]])
a, np.sort(a, axis = 0), np.sort(a, axis = 1)

(array([[ 4,  3,  5,  6],
        [ 1, 12, 11,  9],
        [ 2, 15,  1, 18]]),
 array([[ 1,  3,  1,  6],
        [ 2, 12,  5,  9],
        [ 4, 15, 11, 18]]),
 array([[ 3,  4,  5,  6],
        [ 1,  9, 11, 12],
        [ 1,  2, 15, 18]]))

In [276]:
'''
재배치 resize
'''
a = np.array([[4,3,5,6],[1,12,11,9],[2,15,1,18]])

#print(np.reshape(a, (4, 5)))  # 원 데이터 크기 안에서만 수행 가능
print(np.resize(a, (4, 4)))  # 원 데이터에서 순환하면서 사이즈 조절 가능

[[ 4  3  5  6]
 [ 1 12 11  9]
 [ 2 15  1 18]
 [ 4  3  5  6]]


In [281]:
'''
trim_zeros : 선/후행 0 제거
'''
x = np.array([1,0,0,0,1,2,3,0,1,2,0,0])
np.trim_zeros(x)

array([1, 0, 0, 0, 1, 2, 3, 0, 1, 2])